### ISSUE TITLE
Can't set fan preset modes: failed to call service fan/set_present_mode. required key not provided @ data ['preset_mode']

### ISSUE THREAD

**Issue by jayscovill** [denysdovhan/purifier-card#200]
Trying to set the preset mode on a Levoit Core 400S.

Getting: 
`failed to call service fan/set_present_mode. required key not provided @ data ['preset_mode']`

The documented service call which works is:

```
service: fan.set_preset_mode
data:
  preset_mode: sleep
target:
  device_id: f4230bc48a2d48b2e8e87cefc43950bf
```

The YAML for the card:

```
shortcuts:
  - name: Sleep
    icon: 'mdi:weather-night'
    service: fan.set_preset_mode
    data:
      - preset_mode: sleep 
```

Does the card support this service call?
