### ISSUE TITLE
request support for Xiaomi 4 compact

### ISSUE THREAD

**Issue by mattiabrunello5** [denysdovhan/purifier-card#201]
**Is your feature request related to a problem? Please describe.**
support for Xiaomi 4 compact air purifier 

**Describe the solution you'd like**
add the support for the purifier

**Describe alternatives you've considered**

**Additional context**
now i try to integrate them but the card is empty
![Cattura](https://user-images.githubusercontent.com/66752330/210072875-749817ad-58bd-4a63-94f0-d25c13fde5b7.PNG)

**Comment by PPsyrius** [comment]
@mattiabrunello5 not sure if this helps, but here's my settings for `Xiaomi (Smart) Air Purifier 4 Pro` - its bigger cousin, for example

```yml
type: custom:purifier-card
entity: fan.xiaomi_smart_air_purifier_4_pro
compact_view: false
aqi:
  entiry_id: sensor.xiaomi_smart_air_purifier_4_pro_pm10
  unit: PM2.5
stats:
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_temperature
    unit: °C
    subtitle: Temp
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_humidity
    unit: '%'
    subtitle: Humidity
  - entity_id: sensor.xiaomi_smart_air_purifier_4_pro_filter_life_remaining
    unit: '%'
    subtitle: Filter
shortcuts:
  - name: Speed 1
    icon: mdi:fan-speed-1
    percentage: '33'
  - name: Speed 2
    icon: mdi:fan-speed-2
    percentage: '66'
  - name: Speed 3
    icon: mdi:fan-speed-3
    percentage: '100'
  - name: Silent
    icon: mdi:volume-off
    preset_mode: Silent
  - name: Favorite
    icon: mdi:heart
    preset_mode: Favorite
  - name: Auto
    icon: mdi:auto-mode
    preset_mode: Auto
show_name: true
```
![image](https://github.com/denysdovhan/purifier-card/assets/19505219/72a9150e-9be2-4648-9563-08f4eee1e96c)

**Comment by antalmate12** [comment]
+1 for this

```yaml
type: custom:purifier-card
entity: fan.zhimi_cpa4_8395_air_purifier
compact_view: false
aqi:
  entiry_id: sensor.zhimi_cpa4_8395_pm25_density
  unit: PM2.5
stats:
  - entity_id: sensor.zhimi_cpa4_8395_pm25_density
    subtitle: PM2.5 Density
    value_template: '{{ value }}'
  - entity_id: sensor.zhimi_cpa4_8395_filter_life_level
    unit: '%'
    subtitle: Filter Life
  - entity_id: sensor.zhimi_cpa4_8395_filter_left_time
    unit: ''
    subtitle: Days Left
shortcuts:
  - name: Speed 1
    icon: mdi:fan-speed-1
    percentage: '33'
  - name: Speed 2
    icon: mdi:fan-speed-2
    percentage: '66'
  - name: Speed 3
    icon: mdi:fan-speed-3
    percentage: '100'
  - name: Silent
    icon: mdi:volume-off
    preset_mode: Silent
  - name: Favorite
    icon: mdi:heart
    preset_mode: Favorite
  - name: Auto
    icon: mdi:auto-mode
    preset_mode: Auto
```

The result is the following:
<img width="475" alt="Képernyőfotó 2023-09-12 - 23 44 27" src="https://github.com/denysdovhan/purifier-card/assets/30597152/61cd5293-e1ed-4001-948a-dbd94c04a6a6">

I can't make the slider and the fan-speed shortcuts working

**Comment by javato** [comment]
> +1 for this
> 
> ```yaml
> type: custom:purifier-card
> entity: fan.zhimi_cpa4_8395_air_purifier
> compact_view: false
> aqi:
>   entiry_id: sensor.zhimi_cpa4_8395_pm25_density
>   unit: PM2.5
> stats:
>   - entity_id: sensor.zhimi_cpa4_8395_pm25_density
>     subtitle: PM2.5 Density
>     value_template: '{{ value }}'
>   - entity_id: sensor.zhimi_cpa4_8395_filter_life_level
>     unit: '%'
>     subtitle: Filter Life
>   - entity_id: sensor.zhimi_cpa4_8395_filter_left_time
>     unit: ''
>     subtitle: Days Left
> shortcuts:
>   - name: Speed 1
>     icon: mdi:fan-speed-1
>     percentage: '33'
>   - name: Speed 2
>     icon: mdi:fan-speed-2
>     percentage: '66'
>   - name: Speed 3
>     icon: mdi:fan-speed-3
>     percentage: '100'
>   - name: Silent
>     icon: mdi:volume-off
>     preset_mode: Silent
>   - name: Favorite
>     icon: mdi:heart
>     preset_mode: Favorite
>   - name: Auto
>     icon: mdi:auto-mode
>     preset_mode: Auto
> ```
> 
> The result is the following: <img alt="Képernyőfotó 2023-09-12 - 23 44 27" width="475" src="https://user-images.githubusercontent.com/30597152/267473808-61cd5293-e1ed-4001-948a-dbd94c04a6a6.png">
> 
> I can't make the slider and the fan-speed shortcuts working

Mind under aqi object
It's written "entiry_id" instead of "entity_id". Like this you'll be able to visualize aqi data within the card.

Besides that, I have a Xiaomi 4 Compact and seems that slider cannot work on this device since xiaomi_miot integration creates 2 entities:
One to turn on/off and switch between modes, and a slider to customize manual mode.

That's why your shortcuts dont't work, you need to set a service like following configuration:
```
type: custom:purifier-card
entity: fan.zhimi_cpa4_9859_air_purifier
aqi:
  entity_id: sensor.zhimi_cpa4_9859_pm25_density
  unit: PM2.5
stats:
  - entity_id: sensor.zhimi_cpa4_9859_pm25_density
    subtitle: PM2.5
  - entity_id: sensor.zhimi_cpa4_9859_filter_life_level
    unit: '%'
    subtitle: Filter Life
shortcuts:
  - name: sleep
    icon: mdi:power-sleep
    preset_mode: Sleep
  - name: 25%
    icon: mdi:circle-slice-2
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.zhimi_cpa4_9859_favorite_level
      value: 3
  - name: 50%
    icon: mdi:circle-slice-4
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.zhimi_cpa4_9859_favorite_level
      value: 7
  - name: 75%
    icon: mdi:circle-slice-6
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.zhimi_cpa4_9859_favorite_level
      value: 11
  - name: 100%
    icon: mdi:circle-slice-8
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.zhimi_cpa4_9859_favorite_level
      value: 14
  - name: auto
    icon: mdi:fan-auto
    preset_mode: Auto
show_name: true
show_state: true
show_toolbar: true
compact_view: false

```
