### ISSUE TITLE
Ability to set template for active/inactive style of action buttons

### ISSUE THREAD

**Issue by jacekpaszkowski** [denysdovhan/purifier-card#27]
**Describe the solution you'd like**
I use custom service with custom data for actions eg.

```yaml
        actions:
          - name: Off
            icon: 'mdi:fan-off'
            service: input_select.select_option
            service_data:
              entity_id: input_select.mode_fan_salon_air_purifier
              option: Off
```

In this case i would like to be able to specify template if given button is active or inactive eg.:

```yaml
        actions:
          - name: Off
            icon: 'mdi:fan-off'
            service: input_select.select_option
            service_data:
              entity_id: input_select.mode_fan_salon_air_purifier
              option: Off
            active:
              entity: input_select.select_option
              state: state => state == 'Off'
```

Thank you.
