### ISSUE TITLE
Spinner remains when clicking favorite speed buttons (Air Purifier 2 (mini)).

### ISSUE THREAD

**Issue by chinswain** [denysdovhan/purifier-card#270]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

Spinner remains when clicking favorite speed percentage buttons, fan changes speed ok.
Device is an Air Purifier 2 (mini) (zhimi.airpurifier.m1)

**Screenshots**

![image](https://github.com/denysdovhan/purifier-card/assets/4403897/1cdeece8-bb9b-47de-8119-69a6b56c0a33)

**Versions:**
- Release: Latest
- Browser: chrome
- HomeAssistant version: 2023.9.2

```
type: custom:purifier-card
entity: fan.bedroom_air_purifier
aqi:
  entity_id: sensor.bedroom_air_purifier_pm2_5
stats:
  - entity_id: sensor.bedroom_air_purifier_motor_speed
    unit: RPM
    subtitle: Speed
  - entity_id: sensor.bedroom_air_purifier_filter_lifetime_remaining
    subtitle: Filter
    unit: '%'
shortcuts:
  - name: 25%
    icon: mdi:circle-slice-2
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.bedroom_air_purifier_favorite_level
      value: '5'
  - name: 50%
    icon: mdi:circle-slice-4
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.bedroom_air_purifier_favorite_level
      value: '8'
  - name: 75%
    icon: mdi:circle-slice-6
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.bedroom_air_purifier_favorite_level
      value: '13'
  - name: 100%
    icon: mdi:circle-slice-8
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.bedroom_air_purifier_favorite_level
      value: '16.99'
show_name: true
show_state: true
show_toolbar: true
compact_view: false
```
