### ISSUE TITLE
Target parameter has to be used instead of service_data for shortcuts (wrong parameter order)

### ISSUE THREAD

**Issue by philw07** [denysdovhan/purifier-card#378]
Thanks for this card.
I just noticed that the `target` and `service_data` parameters are in the wrong order in this call.

https://github.com/denysdovhan/purifier-card/blob/b207c37a71996207925793ae9a1c71a60b39d1d0/src/purifier-card.ts#L350

Function signature with different order here:
https://github.com/denysdovhan/purifier-card/blob/b207c37a71996207925793ae9a1c71a60b39d1d0/src/purifier-card.ts#L110

I added shortcuts for oscillation (target not used) and wondered why they weren't working, but then noticed I actually had to use `target` instead of `service_data` due to this issue

```
  - name: Oscillate On
    icon: mdi:arrow-oscillating
    service: fan.oscillate
    target:
      oscillating: true
```
