### ISSUE TITLE
Card takes up some empty space in vertical stack

### ISSUE THREAD

**Issue by Th30wl** [denysdovhan/purifier-card#38]
I have a setup with horizontal stack containing two vertical stacks in order to show cards in two columns. In such setup purifier card is taking up a significant amount of empty space when compact mode is enabled.

Card config:

```
type: 'custom:purifier-card'
entity: fan.air_purifier
stats:
  - attribute: filter_life_remaining
    unit: '%'
    subtitle: Filter
  - attribute: motor_speed
    unit: RPM
    subtitle: Motor
actions:
  - name: Noćni režim
    icon: 'mdi:weather-night'
    speed: Silent
  - name: 25%
    icon: 'mdi:circle-slice-2'
    speed: Favorite
    xiaomi_miio_favorite_level: 3
  - name: 50%
    icon: 'mdi:circle-slice-4'
    speed: Favorite
    xiaomi_miio_favorite_level: 7
  - name: 75%
    icon: 'mdi:circle-slice-6'
    speed: Favorite
    xiaomi_miio_favorite_level: 10
  - name: 100%
    icon: 'mdi:circle-slice-8'
    speed: Favorite
    xiaomi_miio_favorite_level: 14
  - name: Auto
    icon: 'mdi:brightness-auto'
    speed: Auto
show_name: false
show_state: false
show_toolbar: true
compact_view: true
```
![Screenshot 2021-03-15 005620](https://user-images.githubusercontent.com/30597832/111089515-8ae12c00-852c-11eb-8023-597c3e656eb1.png)

- Version: v0.8.0
- Browser: chrome, firefox
- HomeAssistant version: 2021.3.4
