### ISSUE TITLE
Stats not displaying from other entity

### ISSUE THREAD

**Issue by codylv7** [denysdovhan/purifier-card#40]
Latest version of card
Home assistant 2021.3.4

![2021-03-17_20-30-18](https://user-images.githubusercontent.com/40413816/111569431-dd565e80-875f-11eb-9387-5e66e6e364c2.png)
![2021-03-17_20-30-35](https://user-images.githubusercontent.com/40413816/111569434-dfb8b880-875f-11eb-8b0f-fb654ceaac5c.png)

**Comment by codylv7** [comment]
Is this ever going to get fixed? It's never worked since I started using this card

**Comment by denysdovhan** [comment]
You have typos in your configuration. You should use `entity_id` property instead of `entity`.

Here's an example:

```yaml
stats:
  - entity_id: sensor.days_left
    subtitle: Days Left
    unit: days
```
