### ISSUE TITLE
Can't get stats to display

### ISSUE THREAD

**Issue by 26tajeen** [denysdovhan/purifier-card#429]
Thanks for this card! Using the below config but can't get the stats for sensor.office_nanoprotect_filter and sensor.office_pre_filter to show or the aqi to overlay/appear

```
      - card:
        type: 'custom:purifier-card'
        entity: fan.office
        stats:
          - attribute: sensor.office_nanoprotect_filter
            subtitle: Filter Remaining
            unit: '%'
          - attribute: sensor.office_pre_filter
            subtitle: Pre Filter Remaining
            unit: '%'
        shortcuts:
          - name: Sleep
            icon: 'mdi:weather-night'
            preset_mode: sleep
          - name: Medium
            icon: 'mdi:circle-slice-4'
            preset_mode: medium
          - name: Turbo
            icon: 'mdi:circle-slice-8'
            preset_mode: turbo
          - name: Auto
            icon: 'mdi:brightness-auto'
            preset_mode: auto
        aqi: 
          - entity_id: sensor.office_pm2_5
            unit: µg/m3
        show_name: true
        show_state: true
        show_toolbar: true
        compact_view: false
```
![Screenshot 2024-12-21 at 23 20 32](https://github.com/user-attachments/assets/651409f3-bef5-4194-9439-b1b768c8dedf)
![Screenshot 2024-12-21 at 23 20 13](https://github.com/user-attachments/assets/88711612-149c-404c-b9a7-05b5f6ed3bb0)
![Screenshot 2024-12-21 at 23 20 06](https://github.com/user-attachments/assets/d8645981-24a9-478a-8cb5-ce9b89f9f93a)

Am I doing something wrong?

**Comment by shai66** [comment]
In case it helps - in stats instead of attribute you can use entity_id, just check for the corresponding entity id, it could look something like this:
`- card:
        type: 'custom:purifier-card'
        entity: fan.office
        stats:
          - entity_id: sensor.office_nanoprotect_filter
            subtitle: Filter Remaining
            unit: '%'
          - entity_id: sensor.office_pre_filter
            subtitle: Pre Filter Remaining
            unit: '%'
        shortcuts:
            ...
`
in my case with Mi Air purifiers the entity_id would me `sensor.office_nanoprotect_filter_lifetime_remaining`.

**Comment by mrlordziemniak** [comment]
aqi not working on my dashbord too

**Comment by puetsch** [comment]
It's not very obvious from the documentation, but in there: aqi is a dictionary, not a list.

@26tajeen @mrlordziemniak so instead of
```yaml
        aqi: 
          - entity_id: sensor.office_pm2_5
            unit: µg/m3
```

use

```yaml
        aqi: 
          entity_id: sensor.office_pm2_5
          unit: µg/m3
```
