### ISSUE TITLE
Can't get card to show AQI from custom sensor

### ISSUE THREAD

**Issue by julianrinaldi** [denysdovhan/purifier-card#44]
**Before submitting a bug**

[x ] I updated to the latest version available
[x ] I cleared the cache of my browser

**Describe the bug**

I'm trying to get the card to show AQI using a custom sensor that has the state set from an air quality object. It's not displaying on the card though. Is it possible to use the air quality object to display the AQI on the card? I've tried both and it's not working. Here is my code:

```
- type: 'custom:purifier-card'
    entity: fan.master_bedroom_air_purifier
    aqi:
      - entity_id: sensor.master_bedroom_aqi
        unit: µg/m³
```

Is my setup correct?

- Release: 0.8.1
- Browser: All
- HomeAssistant version: core-2021.4.0b4

**Comment by julianrinaldi** [comment]
Nevermind, I figured it out

**Comment by maniacaris** [comment]
> Nevermind, I figured it out

Hey @julianrinaldi! What ended up being the solution? I'm having a similar problem with the aqi and stats objects.

**Comment by julianrinaldi** [comment]
I don't remember specifically what I did to fix it. In my example code the spacing is wrong, but that's just an error with copy and paste or something. It was spaced correctly. Looking at the code that I have that works, I think the - in front of the aqi entity_id was the issue.

```
type: 'custom:purifier-card'
compact_view: true
stats:
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_nitrogen_dioxide
    unit: µg/m³
    subtitle: N0₂
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_particulate_matter_2_5
    unit: µg/m³
    subtitle: PM2.5
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_particulate_matter_10
    unit: µg/m³
    subtitle: PM10
  - entity_id: >-
      sensor.master_bedroom_air_purifier_air_quality_volatile_organic_compounds
    unit: µg/m³
    subtitle: VOC
aqi:
  entity_id: sensor.master_bedroom_aqi
  attribute: state
  unit: µg/m³
entity: fan.master_bedroom_air_purifier
```
