### ISSUE TITLE
Boolean stats doesn't show

### ISSUE THREAD

**Issue by puetsch** [denysdovhan/purifier-card#454]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

Some stats don't render correctlly.

**Steps to reproduce**

This is my "stats" section of the configuration
```yaml
entity: fan.levoit_300s
stats:
  - attribute: screen_status
    subtitle: Screen Status
```

The attribute `screen_status` does exist: `{{ state_attr('fan.levoit_300s','screen_status') }}` returns `false`.

Yet, the card doesn't show it.

**Expected behavior**
Status is shown.

**Screenshots**
<img width="482" alt="Image" src="https://github.com/user-attachments/assets/b5e3c895-cbf1-4d8a-b13a-c29cac98350a" />

**Versions:**

- Release: 2.6.2
- Browser: Edge
- HomeAssistant version:
  - Core 2025.2.4
  - Supervisor 2025.02.1
  - Operating System 14.1
  - Frontend 20250214.0
