### ISSUE TITLE
Bosch Air 2000i/4000i/6000i works well

### ISSUE THREAD

**Issue by alexhass** [denysdovhan/purifier-card#510]
I have an Bosch Air Purifier 4000i and have it integrated successfully. As 2000i and 6000i are the same just smaller/larger it will also work.

![Image](https://github.com/user-attachments/assets/e3e1c8e8-6a15-470f-827e-69010f88f307)

Here is the YAML ready to use:
```
type: custom:purifier-card
entity: fan.air_4000i
stats:
  - entity_id: sensor.air_4000i_zustand_des_hepa_filters
    unit: "%"
    subtitle: Filter Remaining
  - entity_id: sensor.air_4000i_luftqualitat
    subtitle: Air Quality
  - entity_id: sensor.air_4000i_pm25
    unit: µg/m³
    subtitle: PM2.5
shortcuts:
  - name: Silent
    icon: mdi:weather-night
    preset_mode: sleep_wind
  - name: 33%
    icon: mdi:circle-slice-3
    percentage: 33
  - name: 66%
    icon: mdi:circle-slice-5
    percentage: 66
  - name: 100%
    icon: mdi:circle-slice-8
    percentage: 100
  - name: Auto
    icon: mdi:brightness-auto
    preset_mode: auto
show_name: true
show_state: true
show_toolbar: true
compact_view: false
```
