### ISSUE TITLE
Update to 0.10.2 displays blank card

### ISSUE THREAD

**Issue by wkethman** [denysdovhan/purifier-card#62]
I am sorry, I have tried to debug the change in the latest version but recent changes to accommodate showSpeed and showPresetMode are causing the card not to display

**Comment by julianrinaldi** [comment]
I'm having the same issue. Here is my code in case it's helpful.

```
type: custom:purifier-card
compact_view: true
stats:
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_nitrogen_dioxide
    unit: µg/m³
    subtitle: N0₂
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_particulate_matter_2_5
    unit: µg/m³
    subtitle: PM2.5
  - entity_id: sensor.master_bedroom_air_purifier_air_quality_particulate_matter_10
    unit: µg/m³
    subtitle: PM10
  - entity_id: >-
      sensor.master_bedroom_air_purifier_air_quality_volatile_organic_compounds
    unit: µg/m³
    subtitle: VOC
aqi:
  entity_id: sensor.master_bedroom_aqi
  attribute: state
  unit: µg/m³
entity: fan.master_bedroom_air_purifier
```
