### ISSUE TITLE
Samsung Purifier compatibility

### ISSUE THREAD

**Issue by loop2** [denysdovhan/purifier-card#64]
HI! Great card!
I have a samsung purifier that i have connected to HA via Smartthings...
This my code:
```
type: custom:purifier-card
entity: switch.depuratore_aria
aqi:
  - entity_id: sensor.depuratore_aria_air_quality
    unit: 'AQI'
stats:
  - entity_id: sensor.depuratore_aria_dust_level
    unit: 'μg/m^3'
    subtitle: PM10
  - entity_id: sensor.depuratore_aria_fine_dust_level
    unit: 'μg/m^3'
    subtitle: PM2.5
  - entity_id: sensor.depuratore_aria_odor_sensor
    unit: ' '
    subtitle: GAS`
```
The only issue is that i can display the AQI value on the animation... Any idea?
Thanks a lot!

**Comment by denysdovhan** [comment]
You have a typo in your config. This part:

```yaml
aqi:
  - entity_id: sensor.depuratore_aria_air_quality
    unit: 'AQI'
```

should look like this:

```yaml
aqi:
  entity_id: sensor.depuratore_aria_air_quality
  unit: 'AQI'
```
