### ISSUE TITLE
fan.set_percentage needs to be called twice

### ISSUE THREAD

**Issue by mortenmoulder** [denysdovhan/purifier-card#70]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**
I am using the official Xiaomi Miio integration, but it couldn't find the set fan favorite speed service, so I went with `fan.set_percentage` instead. When I go from 1 setting to another (or even the same setting by pressing it twice), it doesn't exactly do that. It turns the fan speed way down and stays there. If I press it again, it goes to the correct fan speed.

Since there is no documentation on the set fan favorite speed service, I had to find an alternative, so I went with the fan speed percentage service.

**Steps to reproduce**

Create two actions like this:

```
actions:
  - name: 25%
    icon: mdi:circle-slice-2
    speed: Favorite
    service: fan.set_percentage
    service_data:
      percentage: 25
  - name: 50%
    icon: mdi:circle-slice-4
    speed: Favorite
    service: fan.set_percentage
    service_data:
      percentage: 50
```

1) Press the 25%
2) Press the 50%

**Expected behavior**
Expected it to change speed after pressing it once.

**Versions:**

- Release: Latest
- Browser: Chrome
- HomeAssistant version: 2021.9
