### ISSUE TITLE
Support for Xiaomi 3C

### ISSUE THREAD

**Issue by grambas** [denysdovhan/purifier-card#82]
Is Xiaomi 3C Air purifier supported? If so, then it could be added to readme file in supported device list

**Comment by JiriFurda** [comment]
Well not entirely. Looks like you can't set speed of the fan via percentage but you need to use rpm instead. That means the round slider is not showing any value and you cannot control the purifier with it.

At least I have managed to get the shortcuts from readme to work:
```
shortcuts:
  - name: 25%
    icon: mdi:circle-slice-2
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.mi_air_purifier_3c_favorite_motor_speed
      value: '780'
  - name: 50%
    icon: mdi:circle-slice-4
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.mi_air_purifier_3c_favorite_motor_speed
      value: '1250'
  - name: 75%
    icon: mdi:circle-slice-6
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.mi_air_purifier_3c_favorite_motor_speed
      value: '1730'
  - name: 100%
    icon: mdi:circle-slice-8
    preset_mode: Favorite
    service: number.set_value
    service_data:
      entity_id: number.mi_air_purifier_3c_favorite_motor_speed
      value: '2200'
```

I'll try to get the slider working as well.
